pom.xml
=> Update DSL version to 6.3.0 (Synonym multi-inheritance, ZonedDateTime code-gen fix)

codefresh.yml
This PR fixes the codefresh.yml file
=> STORY-845 - Migrate to Maven Central

codefresh.yml, pom.xml, settings.xml
=> story 882 task-4613: artifactregistry support

pom.xml
=> pom_update

codefresh.yml
=> Fix cf pipeline tag

pom.xml
=> Update to DSL 9.13.0

src/main/java/com/regnosys/testing/testpack/TestPackFunctionRunner.java, src/main/java/com/regnosys/testing/testpack/TestPackFunctionRunnerImpl.java, src/main/java/com/regnosys/testing/testpack/TestPackFunctionRunnerProviderImpl.java
=> Make test pack infra public

src/main/java/com/regnosys/testing/pipeline/PipelineTestPackWriter.java
=> STORY-884 : Update Output File extension based on Pipeline model Output format

pom.xml, src/main/java/com/regnosys/testing/testpack/TestPackFunctionRunnerImpl.java
=> Update DSL to 9.15.0

pom.xml
=> Update to DSL 9.15.2

pom.xml
Fix tabulation bug - missing close bracket
=> story 959 task:5023 - Fix tabulation bug - missing close bracket

pom.xml
story 959 task-5036: type tabulator bug fix
=> story 959 task-5036: type tabulator bug fix

src/main/java/com/regnosys/testing/pipeline/PipelineTestPackWriter.java
=> Pipeline test pack writer - log transform type

pom.xml
=> Update DSL to 9.20.0

src/main/java/com/regnosys/testing/pipeline/PipelineTestPackWriter.java, src/main/java/com/regnosys/testing/pipeline/PipelineTreeConfig.java, src/test/java/com/regnosys/testing/pipeline/PipelineTestPackWriterTest.java
=> test pack filtering

pom.xml
=> Update DSL to 9.26.0

pom.xml
=> Update DSL to 9.28.2

pom.xml
=> update dsl version

checkstyle.xml, pom.xml, src/main/java/com/regnosys/testing/ModelHelper.java, src/main/java/com/regnosys/testing/pipeline/PipelineConfigWriter.java, src/main/java/com/regnosys/testing/pipeline/PipelineFunctionRunner.java, src/main/java/com/regnosys/testing/pipeline/PipelineModelBuilder.java, src/main/java/com/regnosys/testing/pipeline/PipelineModelWriter.java, src/main/java/com/regnosys/testing/pipeline/PipelineTestPackWriter.java, src/main/java/com/regnosys/testing/pipeline/PipelineTreeBuilder.java, src/main/java/com/regnosys/testing/reports/ReportUtil.java, src/main/java/com/regnosys/testing/schemeimport/AnnotatedRosettaEnumReader.java, src/main/java/com/regnosys/testing/schemeimport/SchemeImporter.java, src/main/java/com/regnosys/testing/schemeimport/SchemeImporterTestHelper.java, src/main/java/com/regnosys/testing/schemeimport/fpml/FpMLSchemeEnumReader.java, src/main/java/com/regnosys/testing/testpack/TestPackFunctionRunnerProviderImpl.java, src/main/java/com/regnosys/testing/testpack/TestPackModelHelperImpl.java, src/main/java/com/regnosys/testing/transform/TransformTestExtension.java, src/test/java/com/regnosys/testing/pipeline/PipelineModelBuilderTest.java, src/test/java/com/regnosys/testing/pipeline/PipelineModelWriterTest.java, src/test/java/com/regnosys/testing/pipeline/PipelineNodeTest.java, src/test/java/com/regnosys/testing/pipeline/PipelineTestHelper.java, src/test/java/com/regnosys/testing/pipeline/PipelineTestPackWriterTest.java, src/test/java/com/regnosys/testing/pipeline/PipelineTreeBuilderTest.java, src/test/java/util/UnusedModelElementFinderTest.java
=> Xtext upgrade

src/main/java/com/regnosys/testing/transform/TransformTestExtension.java
Changed unit testing infrastructure to reduce items in memory.
=> reduced-memory-footprint-of-tests

src/main/java/com/regnosys/testing/transform/TransformTestExtension.java
=> disable-sorting-of-json-option

pom.xml
=> Set nexus timeout to 20 mins

codefresh.yml
=> Add codefresh .m2 cache

src/main/java/com/regnosys/testing/pipeline/PipelineFunctionRunner.java, src/main/java/com/regnosys/testing/pipeline/PipelineTestPackWriter.java, src/main/java/com/regnosys/testing/pipeline/PipelineTreeConfig.java, src/main/java/com/regnosys/testing/testpack/TestPackFunctionRunnerImpl.java, src/main/java/com/regnosys/testing/validation/ValidationSummariser.java
- **reduced-memory-footprint-of-tests**
- **disable-sorting-of-json-option**
- **Update DSL to 9.40.1 (#219)**
- **Update DSL version (#220)**
- **DSL update (#221)**
- **Set nexus timeout to 20 mins (#222)**
- **Added hook to create rich validation report without re-running any validations**
=> add validation summary hook

src/main/java/com/regnosys/testing/reports/ReportTypeSummariser.java
=> Report type summariser

src/main/java/com/regnosys/testing/pipeline/PipelineFunctionRunnerImpl.java, src/main/java/com/regnosys/testing/pipeline/PipelineFunctionRunnerProviderImpl.java, src/main/java/com/regnosys/testing/pipeline/PipelineTestPackWriter.java
=> Function runner logging / exception handling

src/main/java/com/regnosys/testing/pipeline/PipelineModelBuilder.java
=> issue-1163 move code to common

src/main/java/com/regnosys/testing/pipeline/PipelineFunctionRunnerImpl.java, src/main/java/com/regnosys/testing/transform/TransformTestExtension.java, src/test/java/com/regnosys/testing/schemeimport/LatestSchemesImportTest.java
=> Fix assertion of tests

src/test/java/com/regnosys/testing/schemeimport/LatestSchemesImportTest.java
=> Update Checksum in LatestSchemesImportTest

pom.xml
=> Override serialisation fix

src/main/java/com/regnosys/testing/transform/TransformTestExtension.java
=> Add option includeAllPipelinesForFunction to TransformTestExtension

codefresh.yml
=> Fix Codefresh build

src/main/java/com/regnosys/testing/reports/ReportTypeSummariser.java
The creation of the label provider has been fixed.  This class is used to generate a summary of all report attributes.
=> Fix ReportTypeSummariser

pom.xml
=> chore: update dsl

pom.xml
=> Update to DSL 9.67.7

pom.xml
=> [11.85.x] Update DSL version to 9.66.1
